name: philo_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.26.0
  firebase_database: ^10.4.8
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^4.15.7
  http: any
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.4
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # localization
  intl: 
  easy_localization: ^3.0.7
  intl_utils: ^2.8.7
  # for splash screen
  flutter_native_splash: ^2.3.5
  # An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.0.9
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  flutter_offline: ^3.0.1
  dio_smart_retry: ^6.0.0
  smooth_page_indicator: ^1.1.0
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  lottie: ^3.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  firebase_auth: ^4.17.7
  font_awesome_flutter: ^10.1.0
  country_code_picker: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  firebase_messaging: ^14.7.18
  uuid: ^4.4.0
  circular_countdown_timer: ^0.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.2.0


flutter_launcher_icons:  
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_foreground: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
intl_utils: 
  enabled: true

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

    uses-material-design: true

    assets:
      - assets/images/
      #lottie
      - assets/lottie/

    fonts:
      - family: Almarai
        fonts:
          - asset: assets/fonts/Almarai/Almarai-Regular.ttf
            weight: 400
          - asset: assets/fonts/Almarai/Almarai-Bold.ttf
            weight: 700
          - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Almarai/Almarai-Light.ttf
            weight: 300